// Code generated by protoc-gen-go.
// source: things.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	things.proto

It has these top-level messages:
	ClientMessage
	ServerMessage
	Thing
	Component
	Capability
	Property
	Action
	Path
	Value
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type ValueType int32

const (
	ValueType_BOOLEAN ValueType = 1
	ValueType_STRING  ValueType = 2
	ValueType_NUMBER  ValueType = 3
)

var ValueType_name = map[int32]string{
	1: "BOOLEAN",
	2: "STRING",
	3: "NUMBER",
}
var ValueType_value = map[string]int32{
	"BOOLEAN": 1,
	"STRING":  2,
	"NUMBER":  3,
}

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}
func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (x *ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ValueType_value, data, "ValueType")
	if err != nil {
		return err
	}
	*x = ValueType(value)
	return nil
}
func (ValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ThingStatus int32

const (
	ThingStatus_UNKNOWN ThingStatus = 1
)

var ThingStatus_name = map[int32]string{
	1: "UNKNOWN",
}
var ThingStatus_value = map[string]int32{
	"UNKNOWN": 1,
}

func (x ThingStatus) Enum() *ThingStatus {
	p := new(ThingStatus)
	*p = x
	return p
}
func (x ThingStatus) String() string {
	return proto.EnumName(ThingStatus_name, int32(x))
}
func (x *ThingStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ThingStatus_value, data, "ThingStatus")
	if err != nil {
		return err
	}
	*x = ThingStatus(value)
	return nil
}
func (ThingStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ClientMessage_DisconnectReason int32

const (
	ClientMessage_DEVICE_FAILURE ClientMessage_DisconnectReason = 1
	ClientMessage_OK             ClientMessage_DisconnectReason = 2
)

var ClientMessage_DisconnectReason_name = map[int32]string{
	1: "DEVICE_FAILURE",
	2: "OK",
}
var ClientMessage_DisconnectReason_value = map[string]int32{
	"DEVICE_FAILURE": 1,
	"OK":             2,
}

func (x ClientMessage_DisconnectReason) Enum() *ClientMessage_DisconnectReason {
	p := new(ClientMessage_DisconnectReason)
	*p = x
	return p
}
func (x ClientMessage_DisconnectReason) String() string {
	return proto.EnumName(ClientMessage_DisconnectReason_name, int32(x))
}
func (x *ClientMessage_DisconnectReason) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientMessage_DisconnectReason_value, data, "ClientMessage_DisconnectReason")
	if err != nil {
		return err
	}
	*x = ClientMessage_DisconnectReason(value)
	return nil
}
func (ClientMessage_DisconnectReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ClientMessage_ExecutionResult_Status int32

const (
	ClientMessage_ExecutionResult_SUCCESS ClientMessage_ExecutionResult_Status = 1
	ClientMessage_ExecutionResult_FAILURE ClientMessage_ExecutionResult_Status = 2
)

var ClientMessage_ExecutionResult_Status_name = map[int32]string{
	1: "SUCCESS",
	2: "FAILURE",
}
var ClientMessage_ExecutionResult_Status_value = map[string]int32{
	"SUCCESS": 1,
	"FAILURE": 2,
}

func (x ClientMessage_ExecutionResult_Status) Enum() *ClientMessage_ExecutionResult_Status {
	p := new(ClientMessage_ExecutionResult_Status)
	*p = x
	return p
}
func (x ClientMessage_ExecutionResult_Status) String() string {
	return proto.EnumName(ClientMessage_ExecutionResult_Status_name, int32(x))
}
func (x *ClientMessage_ExecutionResult_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ClientMessage_ExecutionResult_Status_value, data, "ClientMessage_ExecutionResult_Status")
	if err != nil {
		return err
	}
	*x = ClientMessage_ExecutionResult_Status(value)
	return nil
}
func (ClientMessage_ExecutionResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 4, 0}
}

type ClientMessage struct {
	Hello                 *ClientMessage_ClientHello           `protobuf:"bytes,1,opt,name=hello" json:"hello,omitempty"`
	Thing                 *Thing                               `protobuf:"bytes,2,opt,name=thing" json:"thing,omitempty"`
	RequestThingsResponse *ClientMessage_RequestThingsResponse `protobuf:"bytes,3,opt,name=requestThingsResponse" json:"requestThingsResponse,omitempty"`
	PropertyChange        *ClientMessage_PropertyChange        `protobuf:"bytes,4,opt,name=propertyChange" json:"propertyChange,omitempty"`
	ExecutionResult       *ClientMessage_ExecutionResult       `protobuf:"bytes,5,opt,name=executionResult" json:"executionResult,omitempty"`
	XXX_unrecognized      []byte                               `json:"-"`
}

func (m *ClientMessage) Reset()                    { *m = ClientMessage{} }
func (m *ClientMessage) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage) ProtoMessage()               {}
func (*ClientMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientMessage) GetHello() *ClientMessage_ClientHello {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *ClientMessage) GetThing() *Thing {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *ClientMessage) GetRequestThingsResponse() *ClientMessage_RequestThingsResponse {
	if m != nil {
		return m.RequestThingsResponse
	}
	return nil
}

func (m *ClientMessage) GetPropertyChange() *ClientMessage_PropertyChange {
	if m != nil {
		return m.PropertyChange
	}
	return nil
}

func (m *ClientMessage) GetExecutionResult() *ClientMessage_ExecutionResult {
	if m != nil {
		return m.ExecutionResult
	}
	return nil
}

type ClientMessage_RequestThingsResponse struct {
	UpdateLock       *uint64  `protobuf:"varint,1,req,name=updateLock" json:"updateLock,omitempty"`
	Things           []*Thing `protobuf:"bytes,2,rep,name=things" json:"things,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ClientMessage_RequestThingsResponse) Reset()         { *m = ClientMessage_RequestThingsResponse{} }
func (m *ClientMessage_RequestThingsResponse) String() string { return proto.CompactTextString(m) }
func (*ClientMessage_RequestThingsResponse) ProtoMessage()    {}
func (*ClientMessage_RequestThingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *ClientMessage_RequestThingsResponse) GetUpdateLock() uint64 {
	if m != nil && m.UpdateLock != nil {
		return *m.UpdateLock
	}
	return 0
}

func (m *ClientMessage_RequestThingsResponse) GetThings() []*Thing {
	if m != nil {
		return m.Things
	}
	return nil
}

type ClientMessage_ClientHello struct {
	UnitId           *string `protobuf:"bytes,1,req,name=unitId" json:"unitId,omitempty"`
	Token            *string `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
	ProtocolVersion  *uint64 `protobuf:"varint,3,req,name=protocolVersion" json:"protocolVersion,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ClientMessage_ClientHello) Reset()                    { *m = ClientMessage_ClientHello{} }
func (m *ClientMessage_ClientHello) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage_ClientHello) ProtoMessage()               {}
func (*ClientMessage_ClientHello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *ClientMessage_ClientHello) GetUnitId() string {
	if m != nil && m.UnitId != nil {
		return *m.UnitId
	}
	return ""
}

func (m *ClientMessage_ClientHello) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *ClientMessage_ClientHello) GetProtocolVersion() uint64 {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return 0
}

type ClientMessage_PropertyChange struct {
	Path             *Path  `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Value            *Value `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ClientMessage_PropertyChange) Reset()                    { *m = ClientMessage_PropertyChange{} }
func (m *ClientMessage_PropertyChange) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage_PropertyChange) ProtoMessage()               {}
func (*ClientMessage_PropertyChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *ClientMessage_PropertyChange) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ClientMessage_PropertyChange) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type ClientMessage_Disconnect struct {
	Reason            *ClientMessage_DisconnectReason `protobuf:"varint,1,req,name=reason,enum=protocol.ClientMessage_DisconnectReason" json:"reason,omitempty"`
	ReasonDescription *string                         `protobuf:"bytes,2,opt,name=reasonDescription" json:"reasonDescription,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *ClientMessage_Disconnect) Reset()                    { *m = ClientMessage_Disconnect{} }
func (m *ClientMessage_Disconnect) String() string            { return proto.CompactTextString(m) }
func (*ClientMessage_Disconnect) ProtoMessage()               {}
func (*ClientMessage_Disconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *ClientMessage_Disconnect) GetReason() ClientMessage_DisconnectReason {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ClientMessage_DEVICE_FAILURE
}

func (m *ClientMessage_Disconnect) GetReasonDescription() string {
	if m != nil && m.ReasonDescription != nil {
		return *m.ReasonDescription
	}
	return ""
}

type ClientMessage_ExecutionResult struct {
	Sequence         *uint64                               `protobuf:"varint,1,req,name=sequence" json:"sequence,omitempty"`
	ErrorReason      *string                               `protobuf:"bytes,2,req,name=errorReason" json:"errorReason,omitempty"`
	Result           *ClientMessage_ExecutionResult_Status `protobuf:"varint,3,req,name=result,enum=protocol.ClientMessage_ExecutionResult_Status" json:"result,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *ClientMessage_ExecutionResult) Reset()         { *m = ClientMessage_ExecutionResult{} }
func (m *ClientMessage_ExecutionResult) String() string { return proto.CompactTextString(m) }
func (*ClientMessage_ExecutionResult) ProtoMessage()    {}
func (*ClientMessage_ExecutionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 4}
}

func (m *ClientMessage_ExecutionResult) GetSequence() uint64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *ClientMessage_ExecutionResult) GetErrorReason() string {
	if m != nil && m.ErrorReason != nil {
		return *m.ErrorReason
	}
	return ""
}

func (m *ClientMessage_ExecutionResult) GetResult() ClientMessage_ExecutionResult_Status {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ClientMessage_ExecutionResult_SUCCESS
}

type ServerMessage struct {
	Hello            *ServerMessage_ServerHello   `protobuf:"bytes,1,opt,name=hello" json:"hello,omitempty"`
	RequestThings    *ServerMessage_RequestThings `protobuf:"bytes,2,opt,name=requestThings" json:"requestThings,omitempty"`
	Action           *ServerMessage_Execute       `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ServerMessage) Reset()                    { *m = ServerMessage{} }
func (m *ServerMessage) String() string            { return proto.CompactTextString(m) }
func (*ServerMessage) ProtoMessage()               {}
func (*ServerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServerMessage) GetHello() *ServerMessage_ServerHello {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *ServerMessage) GetRequestThings() *ServerMessage_RequestThings {
	if m != nil {
		return m.RequestThings
	}
	return nil
}

func (m *ServerMessage) GetAction() *ServerMessage_Execute {
	if m != nil {
		return m.Action
	}
	return nil
}

type ServerMessage_RequestThings struct {
	UpdateLock       *uint64 `protobuf:"varint,1,opt,name=updateLock" json:"updateLock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerMessage_RequestThings) Reset()                    { *m = ServerMessage_RequestThings{} }
func (m *ServerMessage_RequestThings) String() string            { return proto.CompactTextString(m) }
func (*ServerMessage_RequestThings) ProtoMessage()               {}
func (*ServerMessage_RequestThings) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *ServerMessage_RequestThings) GetUpdateLock() uint64 {
	if m != nil && m.UpdateLock != nil {
		return *m.UpdateLock
	}
	return 0
}

type ServerMessage_ServerHello struct {
	Connected        *bool   `protobuf:"varint,1,req,name=connected" json:"connected,omitempty"`
	ErrorMsg         *string `protobuf:"bytes,2,opt,name=error_msg" json:"error_msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerMessage_ServerHello) Reset()                    { *m = ServerMessage_ServerHello{} }
func (m *ServerMessage_ServerHello) String() string            { return proto.CompactTextString(m) }
func (*ServerMessage_ServerHello) ProtoMessage()               {}
func (*ServerMessage_ServerHello) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *ServerMessage_ServerHello) GetConnected() bool {
	if m != nil && m.Connected != nil {
		return *m.Connected
	}
	return false
}

func (m *ServerMessage_ServerHello) GetErrorMsg() string {
	if m != nil && m.ErrorMsg != nil {
		return *m.ErrorMsg
	}
	return ""
}

type ServerMessage_Execute struct {
	Sequence         *uint64                            `protobuf:"varint,1,req,name=sequence" json:"sequence,omitempty"`
	Path             *Path                              `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Parameters       []*ServerMessage_Execute_Parameter `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *ServerMessage_Execute) Reset()                    { *m = ServerMessage_Execute{} }
func (m *ServerMessage_Execute) String() string            { return proto.CompactTextString(m) }
func (*ServerMessage_Execute) ProtoMessage()               {}
func (*ServerMessage_Execute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *ServerMessage_Execute) GetSequence() uint64 {
	if m != nil && m.Sequence != nil {
		return *m.Sequence
	}
	return 0
}

func (m *ServerMessage_Execute) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *ServerMessage_Execute) GetParameters() []*ServerMessage_Execute_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type ServerMessage_Execute_Parameter struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerMessage_Execute_Parameter) Reset()         { *m = ServerMessage_Execute_Parameter{} }
func (m *ServerMessage_Execute_Parameter) String() string { return proto.CompactTextString(m) }
func (*ServerMessage_Execute_Parameter) ProtoMessage()    {}
func (*ServerMessage_Execute_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 2, 0}
}

func (m *ServerMessage_Execute_Parameter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ServerMessage_Execute_Parameter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Thing struct {
	Components       []*Component       `protobuf:"bytes,1,rep,name=components" json:"components,omitempty"`
	Id               *string            `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Name             *string            `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Manufacturer     *string            `protobuf:"bytes,4,req,name=manufacturer" json:"manufacturer,omitempty"`
	MaincomponentId  *string            `protobuf:"bytes,5,req,name=maincomponentId" json:"maincomponentId,omitempty"`
	Status           *ThingStatus       `protobuf:"varint,6,opt,name=status,enum=protocol.ThingStatus" json:"status,omitempty"`
	Attributes       []*Thing_Attribute `protobuf:"bytes,7,rep,name=attributes" json:"attributes,omitempty"`
	DisplayType      *string            `protobuf:"bytes,8,req,name=displayType" json:"displayType,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Thing) Reset()                    { *m = Thing{} }
func (m *Thing) String() string            { return proto.CompactTextString(m) }
func (*Thing) ProtoMessage()               {}
func (*Thing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Thing) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *Thing) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Thing) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Thing) GetManufacturer() string {
	if m != nil && m.Manufacturer != nil {
		return *m.Manufacturer
	}
	return ""
}

func (m *Thing) GetMaincomponentId() string {
	if m != nil && m.MaincomponentId != nil {
		return *m.MaincomponentId
	}
	return ""
}

func (m *Thing) GetStatus() ThingStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ThingStatus_UNKNOWN
}

func (m *Thing) GetAttributes() []*Thing_Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Thing) GetDisplayType() string {
	if m != nil && m.DisplayType != nil {
		return *m.DisplayType
	}
	return ""
}

type Thing_Attribute struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Thing_Attribute) Reset()                    { *m = Thing_Attribute{} }
func (m *Thing_Attribute) String() string            { return proto.CompactTextString(m) }
func (*Thing_Attribute) ProtoMessage()               {}
func (*Thing_Attribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Thing_Attribute) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Thing_Attribute) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Component struct {
	Id               *string       `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name             *string       `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Capabilities     []*Capability `protobuf:"bytes,3,rep,name=capabilities" json:"capabilities,omitempty"`
	Properties       []*Property   `protobuf:"bytes,4,rep,name=properties" json:"properties,omitempty"`
	Actions          []*Action     `protobuf:"bytes,5,rep,name=actions" json:"actions,omitempty"`
	ComponentType    *string       `protobuf:"bytes,6,req,name=componentType" json:"componentType,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Component) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Component) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Component) GetCapabilities() []*Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *Component) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Component) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Component) GetComponentType() string {
	if m != nil && m.ComponentType != nil {
		return *m.ComponentType
	}
	return ""
}

type Capability struct {
	Id               *string     `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Properties       []*Property `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
	Actions          []*Action   `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Capability) Reset()                    { *m = Capability{} }
func (m *Capability) String() string            { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()               {}
func (*Capability) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Capability) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Capability) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Capability) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type Property struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *Value  `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Property) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Property) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Action struct {
	Name             *string             `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Parameters       []*Action_Parameter `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Action) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Action) GetParameters() []*Action_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type Action_Parameter struct {
	Name             *string    `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	ValueType        *ValueType `protobuf:"varint,2,req,name=valueType,enum=protocol.ValueType" json:"valueType,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Action_Parameter) Reset()                    { *m = Action_Parameter{} }
func (m *Action_Parameter) String() string            { return proto.CompactTextString(m) }
func (*Action_Parameter) ProtoMessage()               {}
func (*Action_Parameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *Action_Parameter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Action_Parameter) GetValueType() ValueType {
	if m != nil && m.ValueType != nil {
		return *m.ValueType
	}
	return ValueType_BOOLEAN
}

type Path struct {
	ThingId          *string `protobuf:"bytes,1,req,name=thingId" json:"thingId,omitempty"`
	ComponentId      *string `protobuf:"bytes,2,req,name=componentId" json:"componentId,omitempty"`
	Action           *string `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	Property         *string `protobuf:"bytes,4,opt,name=property" json:"property,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Path) GetThingId() string {
	if m != nil && m.ThingId != nil {
		return *m.ThingId
	}
	return ""
}

func (m *Path) GetComponentId() string {
	if m != nil && m.ComponentId != nil {
		return *m.ComponentId
	}
	return ""
}

func (m *Path) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *Path) GetProperty() string {
	if m != nil && m.Property != nil {
		return *m.Property
	}
	return ""
}

type Value struct {
	ValueType        *ValueType `protobuf:"varint,1,req,name=valueType,enum=protocol.ValueType" json:"valueType,omitempty"`
	Symbol           *string    `protobuf:"bytes,2,req,name=symbol" json:"symbol,omitempty"`
	Value            *string    `protobuf:"bytes,3,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Value) GetValueType() ValueType {
	if m != nil && m.ValueType != nil {
		return *m.ValueType
	}
	return ValueType_BOOLEAN
}

func (m *Value) GetSymbol() string {
	if m != nil && m.Symbol != nil {
		return *m.Symbol
	}
	return ""
}

func (m *Value) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientMessage)(nil), "protocol.ClientMessage")
	proto.RegisterType((*ClientMessage_RequestThingsResponse)(nil), "protocol.ClientMessage.RequestThingsResponse")
	proto.RegisterType((*ClientMessage_ClientHello)(nil), "protocol.ClientMessage.ClientHello")
	proto.RegisterType((*ClientMessage_PropertyChange)(nil), "protocol.ClientMessage.PropertyChange")
	proto.RegisterType((*ClientMessage_Disconnect)(nil), "protocol.ClientMessage.Disconnect")
	proto.RegisterType((*ClientMessage_ExecutionResult)(nil), "protocol.ClientMessage.ExecutionResult")
	proto.RegisterType((*ServerMessage)(nil), "protocol.ServerMessage")
	proto.RegisterType((*ServerMessage_RequestThings)(nil), "protocol.ServerMessage.RequestThings")
	proto.RegisterType((*ServerMessage_ServerHello)(nil), "protocol.ServerMessage.ServerHello")
	proto.RegisterType((*ServerMessage_Execute)(nil), "protocol.ServerMessage.Execute")
	proto.RegisterType((*ServerMessage_Execute_Parameter)(nil), "protocol.ServerMessage.Execute.Parameter")
	proto.RegisterType((*Thing)(nil), "protocol.Thing")
	proto.RegisterType((*Thing_Attribute)(nil), "protocol.Thing.Attribute")
	proto.RegisterType((*Component)(nil), "protocol.Component")
	proto.RegisterType((*Capability)(nil), "protocol.Capability")
	proto.RegisterType((*Property)(nil), "protocol.Property")
	proto.RegisterType((*Action)(nil), "protocol.Action")
	proto.RegisterType((*Action_Parameter)(nil), "protocol.Action.Parameter")
	proto.RegisterType((*Path)(nil), "protocol.Path")
	proto.RegisterType((*Value)(nil), "protocol.Value")
	proto.RegisterEnum("protocol.ValueType", ValueType_name, ValueType_value)
	proto.RegisterEnum("protocol.ThingStatus", ThingStatus_name, ThingStatus_value)
	proto.RegisterEnum("protocol.ClientMessage_DisconnectReason", ClientMessage_DisconnectReason_name, ClientMessage_DisconnectReason_value)
	proto.RegisterEnum("protocol.ClientMessage_ExecutionResult_Status", ClientMessage_ExecutionResult_Status_name, ClientMessage_ExecutionResult_Status_value)
}

var fileDescriptor0 = []byte{
	// 965 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x1e, 0xc9, 0xb6, 0x6c, 0x1d, 0xc7, 0x3f, 0xdd, 0x34, 0x83, 0xab, 0x61, 0x68, 0x71, 0xa7,
	0x69, 0xc8, 0x4c, 0x05, 0x98, 0x9b, 0x5e, 0x40, 0x07, 0xc7, 0x31, 0x34, 0xd3, 0xd4, 0xc9, 0xd8,
	0x49, 0xb8, 0xec, 0x6c, 0xe4, 0x25, 0xd1, 0x54, 0x96, 0x84, 0x76, 0x95, 0xc1, 0x8f, 0xc0, 0x0d,
	0x4f, 0xc0, 0x15, 0x6f, 0xc0, 0xf0, 0x16, 0x3c, 0x15, 0x67, 0x57, 0x92, 0x25, 0x19, 0x9b, 0xe4,
	0xca, 0x5e, 0xed, 0x77, 0xfe, 0xbe, 0xf3, 0x9d, 0xb3, 0xb0, 0x23, 0x6e, 0x5d, 0xff, 0x86, 0xdb,
	0x61, 0x14, 0x88, 0x80, 0x34, 0xd4, 0x8f, 0x13, 0x78, 0xfd, 0x7f, 0x0c, 0x68, 0x8d, 0x3c, 0x97,
	0xf9, 0xe2, 0x3d, 0xe3, 0x9c, 0xde, 0x30, 0x32, 0x80, 0xda, 0x2d, 0xf3, 0xbc, 0xa0, 0xa7, 0x3d,
	0xd3, 0x0e, 0x9a, 0x83, 0xe7, 0x76, 0x86, 0xb5, 0x4b, 0xb8, 0xf4, 0xf4, 0x56, 0x42, 0xc9, 0x67,
	0x50, 0x53, 0xfe, 0x7b, 0xba, 0xb2, 0xe9, 0xe4, 0x36, 0x17, 0xf2, 0x33, 0x39, 0x85, 0xbd, 0x88,
	0xfd, 0x12, 0x33, 0x2e, 0xd4, 0x99, 0x4f, 0x19, 0x0f, 0x03, 0x9f, 0xb3, 0x5e, 0x45, 0xe1, 0x5f,
	0x6d, 0x8b, 0x31, 0xdd, 0x64, 0x44, 0xde, 0x40, 0x1b, 0xf1, 0x21, 0x8b, 0xc4, 0x72, 0x74, 0x4b,
	0xfd, 0x1b, 0xd6, 0xab, 0x2a, 0x37, 0xfb, 0xdb, 0xdc, 0x9c, 0x97, 0xd0, 0xe4, 0x7b, 0xe8, 0xb0,
	0x5f, 0x99, 0x13, 0x0b, 0x37, 0xf0, 0xd1, 0x69, 0xec, 0x89, 0x5e, 0x4d, 0x39, 0x78, 0xb9, 0xcd,
	0xc1, 0xb8, 0x0c, 0xb7, 0xb0, 0x9e, 0xcd, 0xa9, 0x11, 0x80, 0x38, 0x9c, 0x53, 0xc1, 0x4e, 0x03,
	0xe7, 0x23, 0x32, 0xa8, 0x1f, 0x54, 0xc9, 0x53, 0x30, 0x12, 0xf2, 0x91, 0x9d, 0xca, 0x06, 0x76,
	0xac, 0x31, 0x34, 0x8b, 0x64, 0xb6, 0xc1, 0x88, 0x7d, 0x57, 0x9c, 0xcc, 0x95, 0xbd, 0x49, 0x5a,
	0x48, 0x6e, 0xf0, 0x91, 0xf9, 0x68, 0x2e, 0x8f, 0x9f, 0x40, 0x27, 0xb3, 0xbf, 0x62, 0x11, 0xc7,
	0xa4, 0x90, 0x45, 0x8c, 0x63, 0x4d, 0xa0, 0xbd, 0x56, 0xe8, 0xa7, 0x50, 0x0d, 0xa9, 0xb8, 0x55,
	0x7e, 0x9a, 0x83, 0x76, 0x1e, 0xf7, 0x1c, 0xbf, 0xca, 0xa6, 0xdd, 0x51, 0x2f, 0x66, 0xca, 0x6f,
	0x29, 0xad, 0x2b, 0xf9, 0xd9, 0xa2, 0x00, 0xc7, 0x2e, 0x77, 0x02, 0xdf, 0x67, 0x8e, 0x20, 0xaf,
	0xc1, 0x88, 0x18, 0xe5, 0x18, 0x4d, 0x7a, 0x6b, 0x0f, 0x0e, 0xb6, 0x71, 0x95, 0xdb, 0x4c, 0x15,
	0x9e, 0x3c, 0x81, 0x47, 0x89, 0xe5, 0x31, 0xe3, 0x4e, 0xe4, 0x86, 0x92, 0x47, 0x25, 0x14, 0xd3,
	0xfa, 0x43, 0x83, 0xce, 0x1a, 0xb7, 0xa4, 0x0b, 0x0d, 0x2e, 0xb9, 0xf5, 0x1d, 0x96, 0x12, 0xb8,
	0x0b, 0x4d, 0x16, 0x45, 0x41, 0x94, 0xf8, 0x4b, 0x69, 0x78, 0x23, 0xf3, 0x51, 0xbd, 0xab, 0xa8,
	0x7c, 0xec, 0x07, 0xf6, 0xce, 0x9e, 0x09, 0x2a, 0x62, 0xde, 0xef, 0x83, 0x91, 0xfc, 0x23, 0x4d,
	0xa8, 0xcf, 0x2e, 0x47, 0xa3, 0xf1, 0x6c, 0xd6, 0xd5, 0xe4, 0xe1, 0x87, 0xe1, 0xc9, 0xe9, 0xe5,
	0x74, 0xdc, 0xd5, 0xfb, 0x36, 0x74, 0xff, 0x53, 0x0d, 0x81, 0xf6, 0xf1, 0xf8, 0xea, 0x64, 0x34,
	0xfe, 0x90, 0xe1, 0x34, 0x62, 0x80, 0x7e, 0xf6, 0x0e, 0xf1, 0x7f, 0x55, 0xa0, 0x35, 0x63, 0xd1,
	0x1d, 0x8b, 0xee, 0x1f, 0xa6, 0x12, 0x2e, 0x3d, 0x25, 0xfd, 0xff, 0x16, 0x5a, 0xa5, 0x61, 0x49,
	0x87, 0xea, 0xc5, 0x36, 0xdb, 0x92, 0x12, 0xc9, 0x97, 0x60, 0x50, 0x47, 0x24, 0xaa, 0x90, 0x66,
	0x4f, 0xb7, 0x99, 0x25, 0xbc, 0x30, 0xeb, 0x39, 0xb4, 0xca, 0x1e, 0xd6, 0x35, 0xac, 0xa1, 0xb6,
	0xbe, 0x81, 0x66, 0x31, 0xc5, 0x47, 0x60, 0xa6, 0xac, 0xb0, 0x44, 0xa5, 0x0d, 0xf9, 0x49, 0x35,
	0xe9, 0xc3, 0x82, 0xdf, 0xa4, 0xdd, 0xfd, 0x53, 0x83, 0x7a, 0x1a, 0x65, 0x43, 0x57, 0x33, 0x71,
	0xea, 0x1b, 0xc5, 0xf9, 0x1d, 0x40, 0x48, 0x23, 0xba, 0x60, 0x02, 0x35, 0x8e, 0xa5, 0xc8, 0xc1,
	0xf9, 0xe2, 0x9e, 0x52, 0xd0, 0x32, 0xb5, 0xb0, 0x0e, 0xc0, 0x5c, 0x1d, 0xc8, 0x0e, 0x54, 0x7d,
	0xfc, 0x9b, 0x8f, 0x53, 0x2e, 0x7b, 0xb3, 0xff, 0xbb, 0x0e, 0xb5, 0x64, 0x49, 0xbd, 0x04, 0x70,
	0x82, 0x05, 0xce, 0x31, 0x8a, 0x87, 0x23, 0x58, 0x86, 0xdc, 0x2d, 0xa8, 0x2a, 0xbb, 0x43, 0x7e,
	0x74, 0x77, 0x9e, 0xca, 0x30, 0xf3, 0x5d, 0x51, 0xa7, 0xc7, 0xb0, 0xb3, 0xa0, 0x7e, 0xfc, 0x33,
	0x76, 0x20, 0x8e, 0x58, 0x84, 0x7b, 0x29, 0x9d, 0xd8, 0x05, 0x75, 0xfd, 0x95, 0x73, 0x9c, 0xec,
	0x9a, 0xba, 0x78, 0x01, 0x06, 0x57, 0x1a, 0xec, 0x19, 0x48, 0x58, 0x7b, 0xb0, 0xb7, 0xb6, 0x19,
	0x52, 0x81, 0xbe, 0x02, 0xa0, 0x42, 0x44, 0xee, 0x35, 0xd6, 0xc8, 0x7b, 0x75, 0x95, 0xd8, 0x93,
	0x35, 0xa8, 0x3d, 0xcc, 0x10, 0x72, 0x5c, 0xe6, 0x2e, 0x0f, 0x3d, 0xba, 0xbc, 0x58, 0x86, 0xac,
	0xd7, 0x90, 0xa1, 0x24, 0x21, 0x39, 0xe2, 0x7f, 0x09, 0xf9, 0x5b, 0x03, 0x73, 0xbd, 0x56, 0xad,
	0x54, 0x6b, 0x52, 0xf9, 0x21, 0xec, 0x38, 0x34, 0xa4, 0xd7, 0xae, 0xe7, 0x0a, 0x97, 0x65, 0x3d,
	0x7a, 0x5c, 0x20, 0x2c, 0xbb, 0x5d, 0x92, 0x7d, 0xec, 0x66, 0xb2, 0x9a, 0x24, 0xb2, 0xaa, 0x90,
	0xa4, 0xd0, 0xf1, 0x74, 0x6d, 0x91, 0xcf, 0xa1, 0x9e, 0x88, 0x97, 0x23, 0x43, 0x12, 0xd4, 0xcd,
	0x41, 0x43, 0x75, 0x41, 0xf6, 0xa0, 0xb5, 0x22, 0x52, 0xd5, 0x67, 0xa8, 0xac, 0x1d, 0x80, 0x42,
	0xbc, 0x62, 0xd6, 0xe5, 0xd8, 0xfa, 0x43, 0x62, 0x57, 0x36, 0xc7, 0xee, 0xbf, 0x86, 0xc6, 0x0a,
	0x5e, 0xe6, 0xf0, 0x9e, 0x5d, 0xda, 0xff, 0x4d, 0x03, 0x23, 0x2d, 0xa0, 0x6c, 0x68, 0x97, 0x74,
	0x9e, 0x64, 0x67, 0xad, 0x07, 0x2e, 0x08, 0x7b, 0xb8, 0x5d, 0xd8, 0xfb, 0x60, 0xaa, 0x1c, 0x14,
	0x2b, 0xba, 0x5a, 0x8a, 0xbb, 0x6b, 0x79, 0xc8, 0xab, 0xfe, 0x04, 0xaa, 0x6a, 0xc4, 0x3a, 0x50,
	0x57, 0xef, 0xd2, 0xea, 0xa1, 0x41, 0xe1, 0x14, 0x35, 0x9a, 0xb4, 0xb9, 0x5d, 0xda, 0x27, 0xa6,
	0x1c, 0xe4, 0xec, 0xf1, 0x55, 0xcf, 0xae, 0x89, 0xfe, 0x6a, 0xca, 0x79, 0x39, 0x01, 0x6d, 0x6b,
	0x02, 0xd2, 0x25, 0x5f, 0x2e, 0xae, 0x03, 0x2f, 0x0d, 0xb1, 0x12, 0xa0, 0x1a, 0xa2, 0xc3, 0xaf,
	0xc0, 0xcc, 0xb1, 0xb8, 0x8f, 0x8f, 0xce, 0xce, 0x4e, 0xc7, 0xc3, 0x09, 0xee, 0x59, 0xc0, 0x9d,
	0x7d, 0x31, 0x3d, 0x99, 0xfc, 0xd8, 0xd5, 0xe5, 0xff, 0xc9, 0xe5, 0xfb, 0xa3, 0xf1, 0xb4, 0x5b,
	0x39, 0xb4, 0xa0, 0x59, 0x9c, 0x17, 0xb4, 0xb9, 0x9c, 0xbc, 0x9b, 0x9c, 0xfd, 0x84, 0x36, 0x47,
	0xfb, 0xf0, 0x0c, 0x8b, 0xb2, 0xe5, 0xba, 0x72, 0xc4, 0x5c, 0xa6, 0x73, 0xe7, 0xce, 0x59, 0x94,
	0xe7, 0x75, 0xf7, 0xf5, 0x5b, 0xed, 0x5c, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x63, 0xe1, 0x25,
	0xc3, 0x21, 0x09, 0x00, 0x00,
}
